const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM,VirtualConsole}=require('jsdom');
async function open(file,{dark=false,stored=null,blocked=false,source}={}){
 const errors=[],blobs=[],listeners=[],saved=new Map(stored?[['apigee-traffic-lab-theme',stored]]:[]),media={matches:dark,addEventListener:(type,fn)=>listeners.push(fn)};
 const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
 const dom=new JSDOM(source||fs.readFileSync(path.join(__dirname,'..',file),'utf8'),{runScripts:'dangerously',url:'https://example.test/'+file,virtualConsole:vc,beforeParse(w){w.matchMedia=()=>media;Object.defineProperty(w,'localStorage',{get(){if(blocked)throw Error('Storage blocked');return {getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)};}});w.URL.createObjectURL=b=>{blobs.push(b);return 'blob:test';};w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){};}});
 const w=dom.window;await new Promise(resolve=>w.document.readyState==='complete'?resolve():w.addEventListener('load',resolve,{once:true}));
 return {w,errors,saved,$:id=>w.document.getElementById(id),mode:()=>w.document.documentElement.dataset.themeMode,theme:()=>w.document.documentElement.dataset.theme,changeSystem:value=>{media.matches=value;listeners.forEach(fn=>fn({matches:value}));},download:async()=>{w.document.getElementById(file==='lite.html'?'download':'downloadHtml').click();return new Promise(resolve=>{const r=new w.FileReader();r.onload=()=>resolve(r.result);r.readAsText(blobs.at(-1));});}};
}
for(const file of ['index.html','lite.html']){
 test(file+': System reacts live; manual modes persist without changing simulation or seed',async()=>{const x=await open(file,{dark:true});try{
 assert.equal(x.theme(),'dark');assert.equal(x.mode(),'system');x.changeSystem(false);assert.equal(x.theme(),'light');const pass=x.$('passed').textContent,seed=x.$('seed')?.value;
 x.$('themeToggle').click();assert.equal(x.mode(),'light');x.changeSystem(true);assert.equal(x.theme(),'light');x.$('themeToggle').click();assert.equal(x.theme(),'dark');assert.equal(x.saved.get('apigee-traffic-lab-theme'),'dark');assert.equal(x.$('passed').textContent,pass);assert.equal(x.$('seed')?.value,seed);
 x.$('themeToggle').click();assert.equal(x.mode(),'system');x.changeSystem(false);assert.equal(x.theme(),'light');assert.match(x.$('themeToggle').getAttribute('aria-label'),/System \(light\)/);assert.deepEqual(x.errors,[]);
 }finally{x.w.close();}});
 test(file+': stored preferences and cross-tab updates work even when storage is unavailable',async()=>{const x=await open(file,{stored:'light',dark:true}),y=await open(file,{blocked:true,dark:true});try{assert.equal(x.theme(),'light');x.w.dispatchEvent(new x.w.StorageEvent('storage',{key:'apigee-traffic-lab-theme',newValue:'dark'}));assert.equal(x.theme(),'dark');x.w.dispatchEvent(new x.w.StorageEvent('storage',{key:'apigee-traffic-lab-theme',newValue:null}));assert.equal(x.mode(),'system');assert.equal(y.theme(),'dark');y.$('themeToggle').click();assert.equal(y.theme(),'light');assert.deepEqual(x.errors,[]);assert.deepEqual(y.errors,[]);}finally{x.w.close();y.w.close();}});
 test(file+': offline copies retain manual mode and System remains responsive',async()=>{const x=await open(file);let manual,system;try{x.$('themeToggle').click();x.$('themeToggle').click();manual=await open(file,{source:await x.download(),blocked:true,dark:false});assert.equal(manual.theme(),'dark');assert(manual.$('themeToggle'));assert.equal(manual.$(file==='lite.html'?'download':'downloadHtml'),null);x.$('themeToggle').click();system=await open(file,{source:await x.download(),dark:true,blocked:true});assert.equal(system.mode(),'system');assert.equal(system.theme(),'dark');system.changeSystem(false);assert.equal(system.theme(),'light');assert.deepEqual(manual.errors,[]);assert.deepEqual(system.errors,[]);}finally{x.w.close();manual?.w.close();system?.w.close();}});
}
